export interface Doctor {
  name: string;
  specialization: string;
  hospital: string;
}

export const doctorsDB: Doctor[] = [
  { name: "Dr. Prakash Ajmera", specialization: "Sr. Consultant Interventional Cardiologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Kamal Kumar Chawla", specialization: "Interventional Cardiologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. P.S. Gautam", specialization: "Senior Consultant Interventional Cardiologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M. Sudhakar Rao", specialization: "HOD & Sr. Consultant Cardiothoracic Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Harish Badami", specialization: "Sr. Consultant CTVS, Specialist MICS (Robotics)", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. R. Venkatesh", specialization: "Jr. Consultant", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M Surya Narayan", specialization: "Consultant Nephrologist & Renal Transplant Physician", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. B Sangeetha Lakshmi", specialization: "Consultant Nephrologist & Transplant Physician", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. B Rohit Kumar", specialization: "Consultant Neurology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. H Sharan Basappa", specialization: "Consultant Neuro Surgeon (Brain & Spine Surgeon)", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K Raghuram Prasad", specialization: "Consultant Plastic Surgery", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. G.J.D Rao", specialization: "General Medicine & Diabetology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Nithya Chandra", specialization: "Sr. Consultant (General Medicine) physician", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Nallaparaju Divya", specialization: "Consultant Obstetrician, Gynaecologist & Infertility Specialist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. R. Anjani Kumar", specialization: "Sr. Consultant Orthopedic Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Venumadhav Bodla", specialization: "Sr. Consultant Orthopedics, Fellow in Arthroscopy (Shoulder & Knee)", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. B. Suman Kumar", specialization: "Consultant Joint Replacements, Trauma, Ilizarov & Arthroscopic Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K Rajashekar Rao", specialization: "Consultant Pediatrics", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Md Sikander Ali Khan Lodhi", specialization: "Consultant", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rasna Chawla", specialization: "Consultant Ophthalmologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. I Sandeep", specialization: "Consultant, ENT", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K.Radha Ramana Murty", specialization: "Sr. Cardiac Anaesthetist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M Srinivas Reddy", specialization: "Sr. Cardiac Anaesthetist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. B Srinivasulu Reddy", specialization: "Sr. Cardiac Anaesthetist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. BSKVVG Malleswar", specialization: "Sr. Cardiac Anaesthetist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rapaka. Sri Archana", specialization: "Consultant - Anaesthesia", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Alllenki. Prashanthi", specialization: "Jr. Consultant - Anaesthesia", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. P Sudha Poornima", specialization: "Jr. Consultant - Anaesthesia", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Kasina. Sowjanya", specialization: "Jr. Consultant (Specialization: Anaesthesia)", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Yenikepalli. Lavanya", specialization: "Consultant - Anaesthesia", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K. S. Prashanth Kumar", specialization: "Sr. Consultant Radiology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Chandrasekhar Patil", specialization: "Consultant Radiology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Naini ManInder Reddy", specialization: "Consultant Radiology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Shanker Ramya Veni", specialization: "Consultant Radiology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Putcha Anusha", specialization: "Consultant Radiology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Praveen Kotipalli", specialization: "Consultant Pulmonology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rallapaty. Aditya Vadan", specialization: "Consultant Clinical and Interventional Pulmonologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M Lavanya", specialization: "Consultant Dermatologist, Cosmetologist, Trichologist Laser Specialist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. D Subhash Reddy", specialization: "Consultant Dermatology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. V Pramod Kumar", specialization: "Consultant Psychiatry", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M Ranadheer", specialization: "Sr.Consultant & HOD, Nuclear Medicine", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Jilla Swapna", specialization: "Senior Consultant HOD Radiation Oncology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Nadendla. Beulah Elizabeth", specialization: "Jr. Consultant Radiation Oncology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M. Manisegaran", specialization: "Director – Minimal Access, HPB, GI Onco, Bariatric, Colorectal, Redo & Robotic GI Surgeries", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Srinivasa Tejaswini Adada", specialization: "Consultant Medical Oncologist, Hematologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Harish Dara", specialization: "Consultant Surgical Oncologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Venu Gopal Goka", specialization: "Sr. Consultant Neuro & Spine Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Sowmya Kotha", specialization: "Rheumatologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Shekina Polisetti", specialization: "Junior Consultant General Surgery", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Najeshwar R", specialization: "Junior Consultant Orthopaedic Surgery, FASM, FISS", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Ch Srivalli", specialization: "Consultant Medical Oncologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Chandrakanth Chavan", specialization: "HOD – Emergency Medicine", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Hemasree Garlapati", specialization: "Consultant Obstetrician, Cosmetic Gynaecologist, Infertility & Laparoscopic Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. V Deepak Kumar", specialization: "Senior Consultant Physician & Diabetologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Mahesh Bejagam", specialization: "Consultant Surgical Oncologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K. Athirath Reddy", specialization: "Consultant Vascular & Endovascular Surgeon & Diabetic Foot Specialist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. D Sudheer Kumar Reddy", specialization: "Consultant Vascular & Endovascular Surgeon & Diabetic Foot Specialist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Nirusha Pamu", specialization: "Consultant Neonatology", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rangapur Mahesh", specialization: "Consultant Vascular and Endovascular Surgery", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Sunkanna K", specialization: "Consultant Surgical Gastroenterologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. M. Venu Madhav", specialization: "HOD & Senior Consultant Radiologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. K. Vamshi Krishna", specialization: "Consultant Interventional Radiologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rajneesh Reddy Dumpala", specialization: "Consultant Endocrinologist & Diabetologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Varun Kodam", specialization: "Consultant Neurologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. G. Suman Babu", specialization: "Consultant Plastic Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Suraj Kumar Sama", specialization: "Consultant Urologist, Laparoscopic, Robotic & Renal Transplant Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Samanvith Patlori", specialization: "Consultant Gastroenterologist & Hepatologist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Rajesh Lekkala", specialization: "Senior Consultant – Medical Gastroenterology, Hepatology & Therapeutic Endoscopist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. G. Keerthi", specialization: "Consultant Pediatric Surgeon", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Kranthi Kumar Pasupuleti", specialization: "Senior Consultant Gastroenterologist, Hepatologist & Therapeutic Endoscopist", hospital: "Malla Reddy Narayana Multispeciality Hospital" },
  { name: "Dr. Gudivaka Dasarathi", specialization: "Senior Consultant Nephrologist & Transplant Physician", hospital: "Malla Reddy Narayana Multispeciality Hospital" }
];
